language: python
dist: xenial
sudo: false
cache:
  pip: true
branches:
  only:
  - master
  # Tags
  - /^(\d+\.)+\d+(\.\S+)?$/

matrix:
  fast_finish: true
  include:
    - python: '3.5'
    - python: '3.7'
      before_install:
        - pip uninstall -y numpy  # Avoid https://travis-ci.org/github/kernc/backtesting.py/jobs/704292730

    - python: '3.8'
      name: 'Lint, Test w/ Coverage'
      before_script:
        - pip install flake8 coverage
      script:
        - flake8
        - BOKEH_BROWSER=none catchsegv coverage run setup.py test
      after_success:
        - bash <(curl -s https://codecov.io/bash)

    - python: '3.8'
      name: 'Docs'
      stage: deploy
      install:
        - pip install -e .[doc,test]
      script:
        - doc/build.sh
      after_success:
        - if [ "$TRAVIS_BRANCH" = "$TRAVIS_TAG" ]; then bash .github/deploy-gh-pages.sh; fi

before_install:
  - set -e

install:
  - pip install -U pip setuptools
  - pip install -U --pre .[test]

script:
  - BOKEH_BROWSER=none time catchsegv python setup.py test
